version: "3.8"

services:
  
  # testapp
  # testapp

  testapp:
    build:
      context: ./../../
      dockerfile: docker/d.testapp/Dockerfile-testapp
    volumes:
       - ./../../testapp:/usr/src/testapp
    networks:
      - testapp_network
    restart: always
    container_name: testapp
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 2048M
    #     reservations:
    #       memory: 2048M

networks:
  testapp_network:
    driver: bridge
